### ISSUE TITLE
Post appears in sitemap even though it is disabled

### ISSUE THREAD

**Issue by tomkingfisher** [mageplaza/magento-2-blog#226] opened 2019-10-02 10:17 UTC
### Preconditions

1. Magento: 2.3
2. PHP: 7

### Steps to reproduce

1. Create a post
2. Leave post disabled
3. Regenerate Site Map under Marketing -> Site Map

### Expected result

1. Post that is disabled should not be in site map

### Actual result

1. Disabled post is listed within the site map

**Comment by NgoDuVietHung97** [comment] 2019-10-02 10:36
Hi @tomkingfisher,

To solve this problem, please download and replace the attached file:
 - \Mageplaza\Blog\Model\Sitemap.php

[Sitemap.zip](https://github.com/mageplaza/magento-2-blog/files/3680676/Sitemap.zip)

Then, try to generate a site map again and let me know the result.
Thanks

**Comment by bacondeveloper** [comment] 2019-10-17 13:35
Duplicate of this issue https://github.com/mageplaza/magento-2-blog/issues/216

**Comment by Bang512** [comment] 2019-11-01 09:55
Closed due no response within 7 days.

**Closed by Bang512** 2019-11-01 09:55 UTC
