### ISSUE TITLE
Unable to access blog admin after upgrade on Magento 2.2.8

### ISSUE THREAD

**Issue by jfgalano** [mageplaza/magento-2-blog#176] opened 2019-03-29 13:48 UTC
### Preconditions

1. Magento: 2.2.8
2. PHP: 7.1
3. MySQL: 5
4. 

### Steps to reproduce

1. Log into Magento admin 
2. Click on Content->Manage Post
3. Redirect to admin dashboard

### Expected result

1. Log into Magento admin 
2. Click on Content->Manage Post
3. Redirect to Post management page

### Actual result

1. Log into Magento admin 
2. Click on Content->Manage Post
3. Redirect to admin dashboard

**Comment by NgoDuVietHung97** [comment] 2019-04-01 07:21
Hi @jfgalano,
I think you missed something during the process and you should try it again.
If the result is still the same, don't hesitate to let me know.
Thank you!

**Comment by OvalMedia** [comment] 2019-04-09 08:16
I can confirm the issue. It is the same behaviour as in your reports module: https://github.com/mageplaza/magento-2-reports/issues/8

**Comment by NgoDuVietHung97** [comment] 2019-04-09 09:14
Thanks for your feedback, we have updated it to fix this problem.
If you have no further questions, we will close this issue.

**Comment by OvalMedia** [comment] 2019-04-09 14:16
My only question: When will you update the repo?

**Comment by NgoDuVietHung97** [comment] 2019-04-10 01:55
We have updated on the develop branch. You can check back there.
We will update the code on the master branch as soon as possible.
Thank you!

**Comment by roura356a** [comment] 2019-04-30 04:33
Any update on this?

**Comment by NgoDuVietHung97** [comment] 2019-05-06 03:25
Hi @roura356a,

You can check for the latest updates in the develop branch.
Thank you!

**Comment by thaimageplaza** [comment] 2019-05-20 01:29
Closed due to no response within 7 days.

**Closed by thaimageplaza** 2019-05-20 01:29 UTC

**Comment by roura356a** [comment] 2019-05-31 01:08
This problem still happens with the latest 3.0.4 version in Magento 2.2.8.

**Comment by roura356a** [comment] 2019-05-31 01:22
This problem still happens under Magento 2.2.8 and Blog Extension 3.0.5

**Comment by NgoDuVietHung97** [comment] 2019-05-31 01:33
Hi,

We are about to releases the next version of Blog Extension, so please look forward to this.
For now, you can download and use the latest update on branch develop.
Thank you for your understanding!
