### ISSUE TITLE
Infinite loop of redirections because of a unparsable date

### ISSUE THREAD

**Issue by yannicka** [mageplaza/magento-2-blog#170] opened 2019-03-08 08:51 UTC
### Preconditions

1. Magento: 2.3.0
2. PHP: 7.2.14
3. MySQL: MariaDB 10.1.37

### Steps to reproduce

1. Install the module as described in the README: https://github.com/mageplaza/magento-2-blog ("Install via composer")
2. On the backoffice: Content > Manage Posts > Add New Post
3. Set a title
4. Save

### Expected result

1. The post is saved.

### Actual result

An infinite loop of redirections ("The page isn’t redirecting properly" on Firefox or "ERR_TOO_MANY_REDIRECTS" on Chrome):

```
https://mysite.com/admin/mpblog/post/save/key/a_long_token_1/active_tab/post/
https://mysite.com/admin/mpblog/post/edit/id/2/key/a_long_token_2/active_tab/post/
https://mysite.com/admin/mpblog/index/index/key/a_long_token_3/
https://mysite.com/admin/mpblog/index/index/key/a_long_token_3/adminhtml/dashboard
https://mysite.com/admin/mpblog/index/index/key/a_long_token_3/adminhtml/adminhtml/dashboard
https://mysite.com/admin/mpblog/index/index/key/a_long_token_3/adminhtml/adminhtml/adminhtml/dashboard
https://mysite.com/admin/mpblog/index/index/key/a_long_token_3/adminhtml/adminhtml/adminhtml/adminhtml/dashboard
https://mysite.com/admin/mpblog/index/index/key/a_long_token_3/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/dashboard
https://mysite.com/admin/mpblog/index/index/key/a_long_token_3/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/dashboard
https://mysite.com/admin/mpblog/index/index/key/a_long_token_3/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/dashboard
https://mysite.com/admin/mpblog/index/index/key/a_long_token/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/dashboard
...
```

I've tried to reinstall the module multiple times and reinstall vendors, but the problem persists.

## Analyze

I've check the file "var/log/system.log" and I saw:

```
[2019-03-08 08:39:40] main.CRITICAL: Exception message: DateTime::__construct(): Failed to parse time string (8 mars 2019 08:39:40) at position 12 (0): Double time specification
Trace: #0 /var/www/mysite/vendor/magento/framework/Stdlib/DateTime.php(58): DateTime->__construct('8 mars 2019 08:...')
#1 /var/www/mysite/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(2853): Magento\Framework\Stdlib\DateTime->formatDate(Object(Zend_Date), true) #2 /var/www/mysite/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(3081): Magento\Framework\DB\Adapter\Pdo\Mysql->formatDate(Object(Zend_Date))
#3 /var/www/mysite/vendor/magento/framework/Model/ResourceModel/AbstractResource.php(183): Magento\Framework\DB\Adapter\Pdo\Mysql->prepareColumnValue(Array, Object(Zend_Date))
#4 /var/www/mysite/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(542): Magento\Framework\Model\ResourceModel\AbstractResource->_prepareDataForTable(Object(Mageplaza\Blog\Model\Author), 'ddmg_mageplaza_...')
#5 /var/www/mysite/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(818): Magento\Framework\Model\ResourceModel\Db\AbstractDb->_prepareDataForSave(Object(Mageplaza\Blog\Model\Author))
#6 /var/www/mysite/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(414): Magento\Framework\Model\ResourceModel\Db\AbstractDb->updateObject(Object(Mageplaza\Blog\Model\Author))
#7 /var/www/mysite/vendor/magento/framework/Model/AbstractModel.php(648): Magento\Framework\Model\ResourceModel\Db\AbstractDb->save(Object(Mageplaza\Blog\Model\Author))
#8 /var/www/mysite/vendor/mageplaza/magento-2-blog-extension/Model/ResourceModel/Post.php(523): Magento\Framework\Model\AbstractModel->save()
#9 /var/www/mysite/vendor/mageplaza/magento-2-blog-extension/Model/ResourceModel/Post.php(184): Mageplaza\Blog\Model\ResourceModel\Post->saveAuthor()
#10 /var/www/mysite/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(832): Mageplaza\Blog\Model\ResourceModel\Post->_afterSave(Object(Mageplaza\Blog\Model\Post))
#11 /var/www/mysite/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(419): Magento\Framework\Model\ResourceModel\Db\AbstractDb->processAfterSaves(Object(Mageplaza\Blog\Model\Post))
#12 /var/www/mysite/vendor/magento/framework/Model/AbstractModel.php(648): Magento\Framework\Model\ResourceModel\Db\AbstractDb->save(Object(Mageplaza\Blog\Model\Post))
#13 /var/www/mysite/vendor/mageplaza/magento-2-blog-extension/Controller/Adminhtml/Post/Save.php(97): Magento\Framework\Model\AbstractModel->save()#14 /var/www/mysite/generated/code/Mageplaza/Blog/Controller/Adminhtml/Post/Save/Interceptor.php(24): Mageplaza\Blog\Controller\Adminhtml\Post\Save->execute()
#15 /var/www/mysite/vendor/magento/framework/App/Action/Action.php(108): Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->execute()
#16 /var/www/mysite/vendor/magento/module-backend/App/AbstractAction.php(231): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#17 /var/www/mysite/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#18 /var/www/mysite/vendor/magento/framework/Interception/Interceptor.php(138): Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->___callParent('dispatch', Array)
#19 /var/www/mysite/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#20 /var/www/mysite/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#21 /var/www/mysite/vendor/magento/framework/Interception/Interceptor.php(153): Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#22 /var/www/mysite/generated/code/Mageplaza/Blog/Controller/Adminhtml/Post/Save/Interceptor.php(39): Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->___callPlugins('dispatch', Array, NULL)
#23 /var/www/mysite/vendor/magento/framework/App/FrontController.php(159): Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#24 /var/www/mysite/vendor/magento/framework/App/FrontController.php(99): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor))
#25 /var/www/mysite/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#26 /var/www/mysite/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#27 /var/www/mysite/app/code/Infortis/Cgen/Plugin/Magento/Framework/App/FrontController.php(32): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#28 /var/www/mysite/vendor/magento/framework/Interception/Interceptor.php(135): Infortis\Cgen\Plugin\Magento\Framework\App\FrontController->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#29 /var/www/mysite/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#30 /var/www/mysite/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#31 /var/www/mysite/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#32 /var/www/mysite/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#33 /var/www/mysite/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http\Interceptor->launch()
#34 /var/www/mysite/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#35 {main} [] []
```

A date is unparsable because of the french format: `8 mars 2019 08:39:40`.

After inspection, it is those lines on the file `Model/ResourceModel/Author.php` that cause the problem:

https://github.com/mageplaza/magento-2-blog/blob/a955b92885ef8eef7d40524eb4fe5f4e0c3f73cc/Model/ResourceModel/Author.php#L75-L77

By commenting those lines, the post is saved.

I do not know Magento enough to solve this issue. Maybe use `new \DateTime()` instead of `\Zend_Date::now()`?

The PR #164 seems related to this problem.

**Comment by Trabant74** [comment] 2019-03-08 20:34
Just tried to create my first post and I can confirm this issue.

**Comment by thaimageplaza** [comment] 2019-03-11 02:33
Hi,
Thanks for your comments,
This is the solution we offer and it will be updated soon.
Please check file attach.
[Author.zip](https://github.com/mageplaza/magento-2-blog/files/2950453/Author.zip)
Have a nice day!

**Comment by Trabant74** [comment] 2019-03-11 08:45
Thx! Great support, again ;-)

Met vriendelijke groet,

Gerjan Kiewiet


Op ma 11 mrt. 2019 om 03:33 schreef thaimageplaza <notifications@github.com

**Comment by istoutjesdijk** [comment] 2019-03-11 15:56
I have applied the fix but this problem also appears when you click the "Author Information" link in the Magento admin.

**Comment by thaimageplaza** [comment] 2019-03-18 08:16
Hi Istoutjesdijk,

To solve your issue, you need to create a new Post and check again.
Or you can replace your file with the attached file.
These are modified files:
Mageplaza/Blog/Controller/Adminhtml/Author.php

Have a nice day!
[Author.zip](https://github.com/mageplaza/magento-2-blog/files/2976982/Author.zip)

**Comment by LucaTerzaghi** [comment] 2019-03-20 13:28
> Hi Istoutjesdijk,
> 
> To solve your issue, you need to create a new Post and check again.
> Or you can replace your file with the attached file.
> These are modified files:
> Mageplaza/Blog/Controller/Adminhtml/Author.php
> 
> Have a nice day!
> [Author.zip](https://github.com/mageplaza/magento-2-blog/files/2976982/Author.zip)

Had the same issue, now it's working :)
Thank you!

**Comment by thaimageplaza** [comment] 2019-03-26 08:09
Hi,
I will close the issue because the issue has been solved.
Have a nice day!

**Closed by thaimageplaza** 2019-03-26 08:09 UTC

**Comment by istoutjesdijk** [comment] 2019-05-07 13:25
Will this fix be implemented in a future version?

**Comment by NgoDuVietHung97** [comment] 2019-05-08 01:58
Hi @istoutjesdijk,

We have updated them on the develop branch, you can check there.
Have a nice day!

**Comment by erickamoedo** [comment] 2019-05-31 19:48
Hello!
My Magento 2.3.1 crash when i click in:  Content > Author information (http://prntscr.com/nw1zf5)

the error is: 
`[2019-05-31 19:47:45] main.ERROR: DateTime::__construct(): Failed to parse time string (31/05/2019 19:47:45) at position 0 (3): Unexpected character [] []`

**Comment by NgoDuVietHung97** [comment] 2019-06-01 09:35
Hi @erickamoedo,

Maybe these are some mistake here, the file you need to replace is:
Mageplaza/Blog/Model/ResourceModel/Author.php

Please try it again and tell me the result. Thank you!

**Comment by erickamoedo** [comment] 2019-06-03 18:34
> Hi @erickamoedo,
> 
> Maybe these are some mistake here, the file you need to replace is:
> Mageplaza/Blog/Model/ResourceModel/Author.php
> 
> Please try it again and tell me the result. Thank you!



I replaced the author.php on: Mageplaza/Blog/Model/ResourceModel/Author.php

But i get now:


Fatal error: Cannot declare class Mageplaza\Blog\Controller\Adminhtml\Author, because the name is already in use in /home/rikwil28/public_html/app/code/Mageplaza/Blog/Model/ResourceModel/Author.php on line 0

http://prntscr.com/nx503y

Please do you have any suggestion?

**Comment by erickamoedo** [comment] 2019-06-03 18:56
oh my god, i reinstalled all again and it worked perfect. Black magic.

**Comment by NgoDuVietHung97** [comment] 2019-06-04 01:29
Hi @erickamoedo,

If there are problems arising, please feel free to let us know.
We are always to solve them for you.
Have a nice day!
